openapi: 3.0.3

info:
  title: digbeats API
  version: 1.0.0

paths:
  /api/recommendations:
    # 本来はGETメソッドだがrequestBodyを使いたいのでPOSTメソッドに変更
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trackName:
                  type: string
                  example: 夜に駆ける
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  seedTrackName:
                    type: string
                    example: 夜に駆ける
                  recommendedTracks:
                    type: array
                    items:
                      type: object
                      properties:
                        trackName:
                          type: string
                          example: 怪物
                        artistName:
                          type: string
                          example: YOASOBI
                        previewUrl:
                          type: string
                          format: uri
                          example: https://xxx.co/xxx.mp3
                        albumImage:
                          type: string
                          format: uri
                          example: https://xxx.co/image/xxx.jpg
                        artistImage:
                          type: string
                          format: uri
                          example: https://xxx.co/image/xxx.jpg

  /api/favorites/{trackId}:
    post:
      parameters:
        - name: trackId
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: Create
    delete:
      parameters:
        - name: trackId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK

  /api/recommendations/history:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    trackName:
                      type: string
                      example: 怪物
                    artistName:
                      type: string
                      example: YOASOBI
                    previewUrl:
                      type: string
                      format: uri
                      example: https://xxx.co/xxx.mp3
                    albumImage:
                      type: string
                      format: uri
                      example: https://xxx.co/image/xxx.jpg
                    artistImage:
                      type: string
                      format: uri
                      example: https://xxx.co/image/xxx.jpg
                    isLiked:
                      type: boolean
                      example: false

  /api/favorites:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    trackName:
                      type: string
                      example: 怪物
                    artistName:
                      type: string
                      example: YOASOBI
                    previewUrl:
                      type: string
                      format: uri
                      example: https://xxx.co/xxx.mp3
                    albumImage:
                      type: string
                      format: uri
                      example: https://xxx.co/image/xxx.jpg
                    artistImage:
                      type: string
                      format: uri
                      example: https://xxx.co/image/xxx.jpg
                    isLiked:
                      type: boolean
                      example: false
